setwd("C:/Users/mrbre/Desktop/Studia/APU/Lab2/")
install.packages("data.tree")
install.packages("DiagrammeR")
install.packages("formattable")
install.packages("C:/Users/mrbre/Desktop/Studia/APU/Lab2/ahp_0.2.12.tar.gz",repos=NULL,type = "source")
library(ahp)
library(data.tree)
ahpData <- Load("C:/Users/mrbre/Desktop/Studia/APU/Lab2/smartfony.yaml")
Calculate(ahpData)
Visualize(ahpData)
Analyze(ahpData)
AnalyzeTable(ahpData)